/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminZonesIndexRouteImport } from './routes/admin/zones/index'
import { Route as AdminWalletsIndexRouteImport } from './routes/admin/wallets/index'
import { Route as AdminWalletIndexRouteImport } from './routes/admin/wallet/index'
import { Route as AdminVehiclesIndexRouteImport } from './routes/admin/vehicles/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminSubscriptionsIndexRouteImport } from './routes/admin/subscriptions/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminScholarApplicationsIndexRouteImport } from './routes/admin/scholar-applications/index'
import { Route as AdminRidesIndexRouteImport } from './routes/admin/rides/index'
import { Route as AdminRideTypesIndexRouteImport } from './routes/admin/ride-types/index'
import { Route as AdminPaymentsIndexRouteImport } from './routes/admin/payments/index'
import { Route as AdminDriversIndexRouteImport } from './routes/admin/drivers/index'
import { Route as AdminContentIndexRouteImport } from './routes/admin/content/index'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as AdminZonesCreateRouteImport } from './routes/admin/zones/create'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users/$userId'
import { Route as AdminSettingsFeesRouteImport } from './routes/admin/settings/fees'
import { Route as AdminRideTypesRideTypeIdRouteImport } from './routes/admin/ride-types/$rideTypeId'
import { Route as AdminDriversDriverIdRouteImport } from './routes/admin/drivers/$driverId'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as AdminSubscriptionsPlansIndexRouteImport } from './routes/admin/subscriptions/plans/index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'
import { Route as AdminZonesZoneIdEditRouteImport } from './routes/admin/zones/$zoneId/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminZonesIndexRoute = AdminZonesIndexRouteImport.update({
  id: '/zones/',
  path: '/zones/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWalletsIndexRoute = AdminWalletsIndexRouteImport.update({
  id: '/wallets/',
  path: '/wallets/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWalletIndexRoute = AdminWalletIndexRouteImport.update({
  id: '/wallet/',
  path: '/wallet/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVehiclesIndexRoute = AdminVehiclesIndexRouteImport.update({
  id: '/vehicles/',
  path: '/vehicles/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsIndexRoute = AdminSubscriptionsIndexRouteImport.update({
  id: '/subscriptions/',
  path: '/subscriptions/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScholarApplicationsIndexRoute =
  AdminScholarApplicationsIndexRouteImport.update({
    id: '/scholar-applications/',
    path: '/scholar-applications/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminRidesIndexRoute = AdminRidesIndexRouteImport.update({
  id: '/rides/',
  path: '/rides/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRideTypesIndexRoute = AdminRideTypesIndexRouteImport.update({
  id: '/ride-types/',
  path: '/ride-types/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsIndexRoute = AdminPaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDriversIndexRoute = AdminDriversIndexRouteImport.update({
  id: '/drivers/',
  path: '/drivers/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentIndexRoute = AdminContentIndexRouteImport.update({
  id: '/content/',
  path: '/content/',
  getParentRoute: () => AdminRoute,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminZonesCreateRoute = AdminZonesCreateRouteImport.update({
  id: '/zones/create',
  path: '/zones/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsFeesRoute = AdminSettingsFeesRouteImport.update({
  id: '/settings/fees',
  path: '/settings/fees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRideTypesRideTypeIdRoute =
  AdminRideTypesRideTypeIdRouteImport.update({
    id: '/ride-types/$rideTypeId',
    path: '/ride-types/$rideTypeId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminDriversDriverIdRoute = AdminDriversDriverIdRouteImport.update({
  id: '/drivers/$driverId',
  path: '/drivers/$driverId',
  getParentRoute: () => AdminRoute,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscriptionsPlansIndexRoute =
  AdminSubscriptionsPlansIndexRouteImport.update({
    id: '/subscriptions/plans/',
    path: '/subscriptions/plans/',
    getParentRoute: () => AdminRoute,
  } as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminZonesZoneIdEditRoute = AdminZonesZoneIdEditRouteImport.update({
  id: '/zones/$zoneId/edit',
  path: '/zones/$zoneId/edit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/drivers/$driverId': typeof AdminDriversDriverIdRoute
  '/admin/ride-types/$rideTypeId': typeof AdminRideTypesRideTypeIdRoute
  '/admin/settings/fees': typeof AdminSettingsFeesRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/zones/create': typeof AdminZonesCreateRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/admin/content': typeof AdminContentIndexRoute
  '/admin/drivers': typeof AdminDriversIndexRoute
  '/admin/payments': typeof AdminPaymentsIndexRoute
  '/admin/ride-types': typeof AdminRideTypesIndexRoute
  '/admin/rides': typeof AdminRidesIndexRoute
  '/admin/scholar-applications': typeof AdminScholarApplicationsIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/subscriptions': typeof AdminSubscriptionsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/vehicles': typeof AdminVehiclesIndexRoute
  '/admin/wallet': typeof AdminWalletIndexRoute
  '/admin/wallets': typeof AdminWalletsIndexRoute
  '/admin/zones': typeof AdminZonesIndexRoute
  '/admin/zones/$zoneId/edit': typeof AdminZonesZoneIdEditRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/admin/subscriptions/plans': typeof AdminSubscriptionsPlansIndexRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AdminIndexRoute
  '/admin/drivers/$driverId': typeof AdminDriversDriverIdRoute
  '/admin/ride-types/$rideTypeId': typeof AdminRideTypesRideTypeIdRoute
  '/admin/settings/fees': typeof AdminSettingsFeesRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/zones/create': typeof AdminZonesCreateRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/admin/content': typeof AdminContentIndexRoute
  '/admin/drivers': typeof AdminDriversIndexRoute
  '/admin/payments': typeof AdminPaymentsIndexRoute
  '/admin/ride-types': typeof AdminRideTypesIndexRoute
  '/admin/rides': typeof AdminRidesIndexRoute
  '/admin/scholar-applications': typeof AdminScholarApplicationsIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/subscriptions': typeof AdminSubscriptionsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/vehicles': typeof AdminVehiclesIndexRoute
  '/admin/wallet': typeof AdminWalletIndexRoute
  '/admin/wallets': typeof AdminWalletsIndexRoute
  '/admin/zones': typeof AdminZonesIndexRoute
  '/admin/zones/$zoneId/edit': typeof AdminZonesZoneIdEditRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/admin/subscriptions/plans': typeof AdminSubscriptionsPlansIndexRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/drivers/$driverId': typeof AdminDriversDriverIdRoute
  '/admin/ride-types/$rideTypeId': typeof AdminRideTypesRideTypeIdRoute
  '/admin/settings/fees': typeof AdminSettingsFeesRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/zones/create': typeof AdminZonesCreateRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/admin/content/': typeof AdminContentIndexRoute
  '/admin/drivers/': typeof AdminDriversIndexRoute
  '/admin/payments/': typeof AdminPaymentsIndexRoute
  '/admin/ride-types/': typeof AdminRideTypesIndexRoute
  '/admin/rides/': typeof AdminRidesIndexRoute
  '/admin/scholar-applications/': typeof AdminScholarApplicationsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/subscriptions/': typeof AdminSubscriptionsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/vehicles/': typeof AdminVehiclesIndexRoute
  '/admin/wallet/': typeof AdminWalletIndexRoute
  '/admin/wallets/': typeof AdminWalletsIndexRoute
  '/admin/zones/': typeof AdminZonesIndexRoute
  '/admin/zones/$zoneId/edit': typeof AdminZonesZoneIdEditRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/admin/subscriptions/plans/': typeof AdminSubscriptionsPlansIndexRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/'
    | '/admin/drivers/$driverId'
    | '/admin/ride-types/$rideTypeId'
    | '/admin/settings/fees'
    | '/admin/users/$userId'
    | '/admin/zones/create'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/admin/content'
    | '/admin/drivers'
    | '/admin/payments'
    | '/admin/ride-types'
    | '/admin/rides'
    | '/admin/scholar-applications'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/admin/vehicles'
    | '/admin/wallet'
    | '/admin/wallets'
    | '/admin/zones'
    | '/admin/zones/$zoneId/edit'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/admin/subscriptions/plans'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/admin/drivers/$driverId'
    | '/admin/ride-types/$rideTypeId'
    | '/admin/settings/fees'
    | '/admin/users/$userId'
    | '/admin/zones/create'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/admin/content'
    | '/admin/drivers'
    | '/admin/payments'
    | '/admin/ride-types'
    | '/admin/rides'
    | '/admin/scholar-applications'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/admin/vehicles'
    | '/admin/wallet'
    | '/admin/wallets'
    | '/admin/zones'
    | '/admin/zones/$zoneId/edit'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/admin/subscriptions/plans'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/'
    | '/admin/drivers/$driverId'
    | '/admin/ride-types/$rideTypeId'
    | '/admin/settings/fees'
    | '/admin/users/$userId'
    | '/admin/zones/create'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/admin/content/'
    | '/admin/drivers/'
    | '/admin/payments/'
    | '/admin/ride-types/'
    | '/admin/rides/'
    | '/admin/scholar-applications/'
    | '/admin/settings/'
    | '/admin/subscriptions/'
    | '/admin/users/'
    | '/admin/vehicles/'
    | '/admin/wallet/'
    | '/admin/wallets/'
    | '/admin/zones/'
    | '/admin/zones/$zoneId/edit'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/admin/subscriptions/plans/'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/zones/': {
      id: '/admin/zones/'
      path: '/zones'
      fullPath: '/admin/zones'
      preLoaderRoute: typeof AdminZonesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/wallets/': {
      id: '/admin/wallets/'
      path: '/wallets'
      fullPath: '/admin/wallets'
      preLoaderRoute: typeof AdminWalletsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/wallet/': {
      id: '/admin/wallet/'
      path: '/wallet'
      fullPath: '/admin/wallet'
      preLoaderRoute: typeof AdminWalletIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vehicles/': {
      id: '/admin/vehicles/'
      path: '/vehicles'
      fullPath: '/admin/vehicles'
      preLoaderRoute: typeof AdminVehiclesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions/': {
      id: '/admin/subscriptions/'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scholar-applications/': {
      id: '/admin/scholar-applications/'
      path: '/scholar-applications'
      fullPath: '/admin/scholar-applications'
      preLoaderRoute: typeof AdminScholarApplicationsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rides/': {
      id: '/admin/rides/'
      path: '/rides'
      fullPath: '/admin/rides'
      preLoaderRoute: typeof AdminRidesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ride-types/': {
      id: '/admin/ride-types/'
      path: '/ride-types'
      fullPath: '/admin/ride-types'
      preLoaderRoute: typeof AdminRideTypesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments/': {
      id: '/admin/payments/'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/drivers/': {
      id: '/admin/drivers/'
      path: '/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AdminDriversIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/': {
      id: '/admin/content/'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/zones/create': {
      id: '/admin/zones/create'
      path: '/zones/create'
      fullPath: '/admin/zones/create'
      preLoaderRoute: typeof AdminZonesCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/fees': {
      id: '/admin/settings/fees'
      path: '/settings/fees'
      fullPath: '/admin/settings/fees'
      preLoaderRoute: typeof AdminSettingsFeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ride-types/$rideTypeId': {
      id: '/admin/ride-types/$rideTypeId'
      path: '/ride-types/$rideTypeId'
      fullPath: '/admin/ride-types/$rideTypeId'
      preLoaderRoute: typeof AdminRideTypesRideTypeIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/drivers/$driverId': {
      id: '/admin/drivers/$driverId'
      path: '/drivers/$driverId'
      fullPath: '/admin/drivers/$driverId'
      preLoaderRoute: typeof AdminDriversDriverIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subscriptions/plans/': {
      id: '/admin/subscriptions/plans/'
      path: '/subscriptions/plans'
      fullPath: '/admin/subscriptions/plans'
      preLoaderRoute: typeof AdminSubscriptionsPlansIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/zones/$zoneId/edit': {
      id: '/admin/zones/$zoneId/edit'
      path: '/zones/$zoneId/edit'
      fullPath: '/admin/zones/$zoneId/edit'
      preLoaderRoute: typeof AdminZonesZoneIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminDriversDriverIdRoute: typeof AdminDriversDriverIdRoute
  AdminRideTypesRideTypeIdRoute: typeof AdminRideTypesRideTypeIdRoute
  AdminSettingsFeesRoute: typeof AdminSettingsFeesRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminZonesCreateRoute: typeof AdminZonesCreateRoute
  AdminContentIndexRoute: typeof AdminContentIndexRoute
  AdminDriversIndexRoute: typeof AdminDriversIndexRoute
  AdminPaymentsIndexRoute: typeof AdminPaymentsIndexRoute
  AdminRideTypesIndexRoute: typeof AdminRideTypesIndexRoute
  AdminRidesIndexRoute: typeof AdminRidesIndexRoute
  AdminScholarApplicationsIndexRoute: typeof AdminScholarApplicationsIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminSubscriptionsIndexRoute: typeof AdminSubscriptionsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminVehiclesIndexRoute: typeof AdminVehiclesIndexRoute
  AdminWalletIndexRoute: typeof AdminWalletIndexRoute
  AdminWalletsIndexRoute: typeof AdminWalletsIndexRoute
  AdminZonesIndexRoute: typeof AdminZonesIndexRoute
  AdminZonesZoneIdEditRoute: typeof AdminZonesZoneIdEditRoute
  AdminSubscriptionsPlansIndexRoute: typeof AdminSubscriptionsPlansIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminDriversDriverIdRoute: AdminDriversDriverIdRoute,
  AdminRideTypesRideTypeIdRoute: AdminRideTypesRideTypeIdRoute,
  AdminSettingsFeesRoute: AdminSettingsFeesRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminZonesCreateRoute: AdminZonesCreateRoute,
  AdminContentIndexRoute: AdminContentIndexRoute,
  AdminDriversIndexRoute: AdminDriversIndexRoute,
  AdminPaymentsIndexRoute: AdminPaymentsIndexRoute,
  AdminRideTypesIndexRoute: AdminRideTypesIndexRoute,
  AdminRidesIndexRoute: AdminRidesIndexRoute,
  AdminScholarApplicationsIndexRoute: AdminScholarApplicationsIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminSubscriptionsIndexRoute: AdminSubscriptionsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminVehiclesIndexRoute: AdminVehiclesIndexRoute,
  AdminWalletIndexRoute: AdminWalletIndexRoute,
  AdminWalletsIndexRoute: AdminWalletsIndexRoute,
  AdminZonesIndexRoute: AdminZonesIndexRoute,
  AdminZonesZoneIdEditRoute: AdminZonesZoneIdEditRoute,
  AdminSubscriptionsPlansIndexRoute: AdminSubscriptionsPlansIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
